version: '3.7'


services:
    dbpostgres:
      image: postgres@sha256:2c1fb5ffd530cd8d7935ff71959dc548f83763b7c29038d62706b15e58a44285
      container_name: book-store
      restart: always
      ports:
        - '7888:5432'
      environment:
        POSTGRES_PASSWORD: fqQ3nN4L
        POSTGRES_USER: sykros
        POSTGRES_MULTIBLE_DATABASES: zlp
      volumes:
        - D:/2000/bookstore/data:/var/lib/postgresql/data
      networks:
        - 'sky-network'

    cache:
      image: redis:6.2-alpine
      restart: always
      ports:
        - '7000:6379'
      command: redis-server --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      networks:
        - 'sky-network'

#  REDIS_USER=cmVkaXN1c2Vy

#  jaeger:
#    image: jaegertracing/all-in-one
#    container_name: jaeger
#    command:
#      - "--memory.max-traces"
#      - "10000"
#      - "--query.base-path"
#      - "/jaeger/ui"
#      - "--prometheus.server-url"
#      - "http://prometheus:9090"
#    deploy:
#      resources:
#        limits:
#          memory: 300M
#    restart: unless-stopped
#    ports:
#      - '14268:14268'                   # Jaeger UI
#      - '4317'                          # OTLP gRPC default port
#      - '4318'                          # OTLP HTTP default port
#      - '16686:16686'
#      - '14250:14250'
#    environment:
#      - COLLECTOR_OTLP_ENABLED=true
#      - METRICS_STORAGE_TYPE=prometheus
#    networks:
#      - 'sky-network'
#
#
#  prometheus:
#    image: prom/prometheus
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - --web.console.templates=/etc/prometheus/consoles
#      - --web.console.libraries=/etc/prometheus/console_libraries
#      - --storage.tsdb.retention.time=1h
#      - --config.file=/etc/prometheus/prometheus.yml
#      - --storage.tsdb.path=/prometheus
#      - --web.enable-lifecycle
#      - --web.route-prefix=/
#      - --enable-feature=exemplar-storage
#    ports:
#      - '9090:9090'
#    networks:
#      - 'sky-network'
#
#  otel-collector:
#    image: otel/opentelemetry-collector-contrib:0.76.1
#    command : [ --config=/etc/otel-collector-config.yaml ]
#    volumes:
#      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
#    ports:
#      - '1888:1888' # pprof extension
#      - '8888:8888' # Prometheus metrics exposed by the collector
#      - '8889:8889' # Prometheus exporter metrics
#      - '13133:13133' # health_check extension
#      - '4317:4317' # OTLP gRPC receiver
#      - '4318:4318' # OTLP http receiver
#      #      - '55679:55679' # zpages extension
#      #      - '55681:55681'
#      - '9464:9464'
#    networks:
#      - 'sky-network'

networks:
  sky-network:
    name: sky-network

