version: '3.7'


services:
    dbpostgres:
      image: postgres@sha256:2c1fb5ffd530cd8d7935ff71959dc548f83763b7c29038d62706b15e58a44285
      container_name: book-store
      restart: always
      ports:
        - '7888:5432'
      environment:
        POSTGRES_PASSWORD: fqQ3nN4L
        POSTGRES_USER: sykros
        POSTGRES_MULTIBLE_DATABASES: zlp
      volumes:
        - D:/2000/bookstore/data:/var/lib/postgresql/data
      networks:
        - 'sky-network'

    cache:
      image: redis:6.2-alpine
      restart: always
      ports:
        - '7000:6379'
      command: redis-server --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      networks:
        - 'sky-network'

    app:
      build: .
      command: /godocker dev
      container_name: oline-course-platform
      ports:
        - "5000:8888"

    datadog:
#      image: datadog/agent:latest
      build:
        context: ./config/dd
        dockerfile: Dockerfile
      env_file:
        - ./config/dd/.env
      pid: host
      environment:
        - DD_API_KEY=drake_dd
        - DD_LOGS_ENABLED=true
        - DD_APM_NON_LOCAL_TRAFFIC=true
      ports:
        - "8126:8126"
        - "5052:5052"
        - "5002:9876"
        - "5012:9877"
      stdin_open: true
      tty: true
#      volumes:
#        - ./var/run/docker.sock:/var/run/docker.sock
#        - ./proc/:/host/proc/:ro
#        - ./sys/fs/cgroup:/host/sys/fs/cgroup:ro
#        - ./var/lib/docker/containers:/var/lib/docker/containers:ro



networks:
  sky-network:
    name: sky-network

